// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-6hHu5lomZ_pBbc7ajq86nvHLxPzTdQ',
    appId: '1:343821362827:web:68af888a7f1c52c1b0968e',
    messagingSenderId: '343821362827',
    projectId: 'pakeaja-app',
    authDomain: 'pakeaja-app.firebaseapp.com',
    storageBucket: 'pakeaja-app.firebasestorage.app',
    measurementId: 'G-PEYS5P94P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCENDcGvDJwL3dPP1umiKdt7Q3n3_d09o',
    appId: '1:343821362827:android:f584a17a621b9fbbb0968e',
    messagingSenderId: '343821362827',
    projectId: 'pakeaja-app',
    storageBucket: 'pakeaja-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCboCSj-xHex4MqEAJNXZ4RhUKGKchIGqU',
    appId: '1:343821362827:ios:14311a9a251d20cbb0968e',
    messagingSenderId: '343821362827',
    projectId: 'pakeaja-app',
    storageBucket: 'pakeaja-app.firebasestorage.app',
    iosBundleId: 'com.example.pakeaja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCboCSj-xHex4MqEAJNXZ4RhUKGKchIGqU',
    appId: '1:343821362827:ios:14311a9a251d20cbb0968e',
    messagingSenderId: '343821362827',
    projectId: 'pakeaja-app',
    storageBucket: 'pakeaja-app.firebasestorage.app',
    iosBundleId: 'com.example.pakeaja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ-6hHu5lomZ_pBbc7ajq86nvHLxPzTdQ',
    appId: '1:343821362827:web:4fcaf34db97eeafcb0968e',
    messagingSenderId: '343821362827',
    projectId: 'pakeaja-app',
    authDomain: 'pakeaja-app.firebaseapp.com',
    storageBucket: 'pakeaja-app.firebasestorage.app',
    measurementId: 'G-YFZBW9DRPC',
  );
}
